import Foundation

public extension Array where Element == ResolvedEntry {

    /// Audit projected depreciation vs. postings in these resolved entries.
    ///
    /// - projections: expected per-entity slices (e.g. from EntityStore.projectDepreciation).
    /// - configs:     resolved configs (for the posting account used by each entity).
    /// - dateOf:      how to extract a `Date` from a `ResolvedEntry` (handles DateSpecification cases).
    func auditDepreciation(
        projections: [EntityKey: [DepreciationSlice]],
        configs: [EntityKey: DepreciationConfig],
        granularity: DepreciationGranularity,
        calendar: Calendar = .init(identifier: .gregorian),
        tolerance: Decimal = 0.01,
        tolerateAggregateIntraQuarter: Bool = true,
        dateOf: (ResolvedEntry) -> Date
    ) -> DepreciationAuditReport {

        var items: [DepreciationAuditItem] = []

        func qkey(_ d: Date) -> QKey {
            let c = calendar.dateComponents([.year, .month], from: d)
            let m = (c.month ?? 1)
            return QKey(y: c.year ?? 1970, q: ((m - 1) / 3) + 1)
        }

        func qkey(for slice: DepreciationSlice) -> QKey {
            let postingDate = calendar.date(byAdding: .day, value: -1, to: slice.periodEnd) ?? slice.periodEnd
            return qkey(postingDate)
        }

        var quarterExpected: [QKey: Decimal] = [:]
        var quarterActual: [QKey: Decimal] = [:]

        for (ekey, slices) in projections {
            guard let cfg = configs[ekey] else { continue }
            let account = cfg.account

            if granularity == .monthly || granularity == .quarterly {
                for s in slices {
                    let k = qkey(for: s)
                    quarterExpected[k, default: 0] += s.depreciation

                    let actuals = actualsForPeriod(
                        entity: ekey,
                        account: account,
                        from: s.periodStart,
                        to: s.periodEnd,
                        dateOf: dateOf
                    )
                    quarterActual[k, default: 0] += actuals.actual
                }
            }

            for s in slices {
                let actuals = actualsForPeriod(
                    entity: ekey,
                    account: account,
                    from: s.periodStart,
                    to: s.periodEnd,
                    dateOf: dateOf
                )

                let expected = s.depreciation
                let actual = actuals.actual
                let deltaMagnitude = (actual - expected).magnitude

                var coverage: DepreciationCoverage
                var note: String? = nil

                if deltaMagnitude == 0 {
                    coverage = .exact
                } else if deltaMagnitude <= tolerance {
                    coverage = .withinTolerance
                } else if granularity == .monthly && tolerateAggregateIntraQuarter {
                    let k = qkey(for: s)
                    if let qExp = quarterExpected[k],
                       let qAct = quarterActual[k],
                       (qAct - qExp).magnitude <= tolerance {
                        coverage = .aggregateCovered
                        note = "Quarter total matches; month differs but covered by quarter-end booking."
                    } else {
                        coverage = .none
                    }
                } else {
                    coverage = .none
                }

                let actualAutoGenerated = actuals.actualAutoGenerated
                let actualManual = actuals.actualManual

                let generatedCoverage = Swift.min(expected, actualAutoGenerated)
                let remainingExpectedAfterGenerated = Swift.max(expected - generatedCoverage, Decimal.zero)

                let surplusAutoGenerated = Swift.max(actualAutoGenerated - expected, Decimal.zero)
                let surplusManual = Swift.max(actualManual - remainingExpectedAfterGenerated, Decimal.zero)

                items.append(
                    DepreciationAuditItem(
                        entity: ekey,
                        account: account,
                        periodStart: s.periodStart,
                        periodEnd: s.periodEnd,
                        expected: expected,
                        actual: actual,
                        actualAutoGenerated: actualAutoGenerated,
                        actualManual: actualManual,
                        delta: (actual - expected),
                        coverage: coverage,
                        surplusAutoGenerated: surplusAutoGenerated,
                        surplusManual: surplusManual,
                        details: actuals.details,
                        note: note
                    )
                )
            }
        }

        return DepreciationAuditReport(items: items, tolerance: tolerance)
    }

    private func actualsForPeriod(
        entity: EntityKey,
        account: AccountKey,
        from: Date,
        to: Date,
        dateOf: (ResolvedEntry) -> Date
    ) -> DepreciationPeriodActuals {

        var actual: Decimal = 0
        var actualAutoGenerated: Decimal = 0
        var actualManual: Decimal = 0
        var details: [DepreciationMatchDetail] = []

        for e in self {
            let d = dateOf(e)
            if d < from || d >= to { continue }

            let origin = depreciationOrigin(for: e)

            for l in e.lines where l.entity == entity && l.account == account {
                let amt = l.amount.magnitude

                actual += amt

                switch origin {
                case .autoGenerated:
                    actualAutoGenerated += amt
                case .manual:
                    actualManual += amt
                }

                details.append(
                    .init(
                        entryId: entryIdString(e),
                        date: d,
                        amount: amt,
                        origin: origin,
                        note: depreciationOriginNote(for: e, origin: origin)
                    )
                )
            }
        }

        return DepreciationPeriodActuals(
            actual: actual,
            actualAutoGenerated: actualAutoGenerated,
            actualManual: actualManual,
            details: details
        )
    }
}

private func depreciationOrigin(for e: ResolvedEntry) -> DepreciationMatchOrigin {
    let details = e.details?.lowercased() ?? ""

    if details.contains("auto-generated") {
        return .autoGenerated
    }

    return .manual
}

private func depreciationOriginNote(
    for e: ResolvedEntry,
    origin: DepreciationMatchOrigin
) -> String? {
    switch origin {
    case .autoGenerated:
        return "auto-generated depreciation entry"
    case .manual:
        return nil
    }
}

private func entryIdString(_ e: ResolvedEntry) -> String? {
    return String(describing: e.id)
}

