import Foundation

public enum DepreciationCoverage: String, Codable, Sendable {
    case exact, withinTolerance, aggregateCovered, none
}

public enum DepreciationMatchOrigin: String, Codable, Sendable {
    case autoGenerated
    case manual

    public var displayLabel: String {
        switch self {
        case .autoGenerated:
            return "auto-generated"
        case .manual:
            return "manual"
        }
    }
}

public struct DepreciationMatchDetail: Codable, Sendable {
    public let entryId: String?
    public let date: Date
    public let amount: Decimal
    public let origin: DepreciationMatchOrigin
    public let note: String?
}

public struct DepreciationAuditItem: Codable, Sendable {
    public let entity: EntityKey
    public let account: AccountKey
    public let periodStart: Date
    public let periodEnd: Date

    public let expected: Decimal
    public let actual: Decimal
    public let actualAutoGenerated: Decimal
    public let actualManual: Decimal

    public let delta: Decimal
    public let coverage: DepreciationCoverage

    public let surplusAutoGenerated: Decimal
    public let surplusManual: Decimal

    public let details: [DepreciationMatchDetail]
    public let note: String?
}

public struct DepreciationAuditReport: Codable, Sendable {
    public let items: [DepreciationAuditItem]
    public let tolerance: Decimal

    public var failures: [DepreciationAuditItem] {
        items.filter { $0.coverage == .none }
    }
}

internal struct DepreciationPeriodActuals {
    let actual: Decimal
    let actualAutoGenerated: Decimal
    let actualManual: Decimal
    let details: [DepreciationMatchDetail]
}

internal struct QKey: Hashable {
    let y: Int
    let q: Int

    public init(
        y: Int,
        q: Int
    ) {
        self.y = y
        self.q = q
    }
}
