import Accounting
import Foundation
import Writers

public enum DepreciationEntryWriter {
    public struct Options: Sendable {
        public var tz: TimeZone
        public var tolerance: Decimal
        public var safe: SafeWriteOptions
        public var fractionDigits: Int
        public var contentOverwriteMode: ContentOverwriteMode

        public init(
            tz: TimeZone,
            tolerance: Decimal,
            safe: SafeWriteOptions,
            fractionDigits: Int = 2,
            contentOverwriteMode: ContentOverwriteMode = .append
        ) {
            self.tz = tz
            self.tolerance = tolerance
            self.safe = safe
            self.fractionDigits = fractionDigits
            self.contentOverwriteMode = contentOverwriteMode
        }
    }

    @inline(__always)
    public static func roundDecimal(_ x: Decimal, scale: Int) -> Decimal {
        AccountingMoney.round(x, scale: scale)
    }

    // @inline(__always)
    // public static func roundDecimal(_ x: Decimal, scale: Int) -> Decimal {
    //     var v = x
    //     var out = Decimal()
    //     NSDecimalRound(&out, &v, scale, .plain)
    //     return out
    // }

    @inline(__always)
    public static func fmtDecimal(_ x: Decimal, digits: Int) -> String {
        let nf = NumberFormatter()
        nf.locale = Locale(identifier: "en_US_POSIX")
        nf.numberStyle = .decimal
        nf.minimumFractionDigits = digits
        nf.maximumFractionDigits = digits
        nf.minimumIntegerDigits = 1
        return nf.string(from: x as NSDecimalNumber) ?? x.description
    }

    /// - Returns: number of entries written (0 if nothing to write).
    public static func writeMissingForMonth(
        monthStart: Date,
        project: EntryCompilerProject,
        settings: EntryCompilerSettings,
        entities: EntityStore,
        report: DepreciationAuditReport,
        projectRoot: URL,
        options: Options,
        verbose: Bool = false
    ) throws -> Int {
        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = options.tz

        let canonicalMonthStart = DepreciationPostingWindow.monthStart(
            for: monthStart,
            calendar: cal
        )

        let entriesRoot = projectRoot.appendingPathComponent("entries", isDirectory: true)
        let yqmMonth = try yqm(for: canonicalMonthStart, tz: options.tz)
        let targetPath = makeEntryPath(root: entriesRoot, yqm: yqmMonth, filename: "depreciation")

        var nextId = try IDScanner.suggestNextEntryID(project: project, settings: settings)

        @inline(__always)
        func allocID() -> Int {
            defer { nextId += 1 }
            return nextId
        }

        var chunks: [String] = []
        chunks.reserveCapacity(report.items.count)

        let monthLabel = "\(yqmMonth.year)-\(String(format: "%02d", yqmMonth.month))"

        for item in report.items {
            guard item.coverage == .none else { continue }

            guard DepreciationPostingWindow.belongsToMonth(
                item,
                monthStart: canonicalMonthStart,
                calendar: cal
            ) else {
                continue
            }

            let rawPost = DepreciationPostingWindow.postingDate(
                for: item,
                calendar: cal
            )

            let missingRaw = item.expected - item.actual
            let missing = roundDecimal(missingRaw, scale: options.fractionDigits)
            guard missing > options.tolerance else { continue }

            guard let cfg = entities.byFull[item.entity]?.depreciation else { continue }

            let dateStr = isoDate(rawPost)

            let entityIdent = item.entity.identifier(displaying: .fullchain)
            let debitAccount = cfg.account.code
            let creditAccount = cfg.contra.code

            let eid = allocID()
            let amt = fmtDecimal(missing, digits: options.fractionDigits)

            chunks.append("""
            entry {
                id = \(eid)

                date = \(dateStr)

                sort adjusting

                details {
                    Depreciation \(entityIdent) \(monthLabel)
                    Auto-generated
                }

                for (\(entityIdent)) in (\(debitAccount)) {
                    debit = \(amt)
                }

                for (\(entityIdent)) in (\(creditAccount)) {
                    credit = \(amt)
                }
            }
            """)
        }

        guard !chunks.isEmpty else { return 0 }
        try ensureDir(targetPath.deletingLastPathComponent())

        let generatedBlock = """
        // AUTOGENERATED by ec depreciation write for \(monthLabel)

        \(chunks.joined(separator: "\n\n"))
        """

        let separator = """

        // AUTO-APPENDED DEPRECIATION ENTRIES
        // ec depreciation write
        // month: \(monthLabel)

        """

        let sf = SafeFile(targetPath)

        let writeResult = try sf.write(
            generatedBlock,
            content: options.contentOverwriteMode,
            separator: separator,
            options: options.safe
        )

        if verbose {
            print(writeResult)
        }

        return chunks.count
    }
}
